FROM php:7.3-fpm-alpine

COPY conf.d/php.ini /usr/local/etc/php/

RUN apk upgrade --update && apk add \
        coreutils \
        autoconf \
        build-base \
        freetype-dev \
        libjpeg-turbo-dev \
        libltdl \
        libmcrypt-dev \
        libpng-dev \
        icu-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        git \
        libsodium-dev \
        postgresql-dev \
    && docker-php-ext-install -j$(nproc) iconv intl pdo_mysql pdo_pgsql soap xsl zip bcmath \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

RUN pecl install redis-4.3.0 \
    && pecl install xdebug-2.7.0 \
    && pecl install libsodium-2.0.21 \
    && pecl install mcrypt-1.0.2 \
    && pecl install ast-1.0.3 \
    && docker-php-ext-enable redis xdebug
